project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "oil price analysis"
  author:
    - Lanyu He
    - Lingjun Guo
  repo-url: https://github.com/lh3238/oilprice
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: minty
    code-fold: true


